function res=g1(q0,w0)
% Cette fonction calcul g (membre de droite de ED) pour le cas 1,
% c est a dire lorsque l'auto roule et ne glisse pas.
% avec
%	q0	:   conditions initiales [q(t0)]
%	w0	:   la vitesse angulaire initiale (en z), elle est supposée constante

res = [ ... 
    0 ...
    0 ...
    q0(1) ...
    q0(2) ...
    w0 ...
];
